// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aserto/authorizer/v2/api/decision_logs.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// represents a decision that an authorizer performed in the past
type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                             // unique id, replay a decision starting with this, also useful to de-dup
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                               // UTC time when the decision was made
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                                                                                         // Policy path used in decision
	User          *DecisionUser          `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                                                                                         // info about user for whom the decision as made
	Policy        *DecisionPolicy        `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`                                                                                     // info about policy used for the decision
	Outcomes      map[string]bool        `protobuf:"bytes,6,rep,name=outcomes,proto3" json:"outcomes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`      // outcome of the decisions specified in the policy context
	Resource      *structpb.Struct       `protobuf:"bytes,7,opt,name=resource,proto3" json:"resource,omitempty"`                                                                                 // the resource context used in a decision
	Annotations   map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // annotations that may be added to a decision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_aserto_authorizer_v2_api_decision_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_api_decision_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_api_decision_logs_proto_rawDescGZIP(), []int{0}
}

func (x *Decision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Decision) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Decision) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Decision) GetUser() *DecisionUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Decision) GetPolicy() *DecisionPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Decision) GetOutcomes() map[string]bool {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *Decision) GetResource() *structpb.Struct {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Decision) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// information about a user on behalf of whom a decision was made
type DecisionUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *IdentityContext       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // identity context used in the decision
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`           // id of the user the identity resolved to
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`     // convenience human-readable identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionUser) Reset() {
	*x = DecisionUser{}
	mi := &file_aserto_authorizer_v2_api_decision_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionUser) ProtoMessage() {}

func (x *DecisionUser) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_api_decision_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionUser.ProtoReflect.Descriptor instead.
func (*DecisionUser) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_api_decision_logs_proto_rawDescGZIP(), []int{1}
}

func (x *DecisionUser) GetContext() *IdentityContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DecisionUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DecisionUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// information about a policy used in a decision
type DecisionPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Context         *PolicyContext         `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`                                        // policy context used in the decision
	RegistryService string                 `protobuf:"bytes,2,opt,name=registry_service,json=registryService,proto3" json:"registry_service,omitempty"` // registry service where policy was retrieved from (e.g. opcr.io)
	RegistryImage   string                 `protobuf:"bytes,3,opt,name=registry_image,json=registryImage,proto3" json:"registry_image,omitempty"`       // image of the policy in the registry, including org (e.g. acmecorp/peoplefinder-abac)
	RegistryTag     string                 `protobuf:"bytes,4,opt,name=registry_tag,json=registryTag,proto3" json:"registry_tag,omitempty"`             // tag of the policy image (e.g. 0.8.2 or latest)
	RegistryDigest  string                 `protobuf:"bytes,5,opt,name=registry_digest,json=registryDigest,proto3" json:"registry_digest,omitempty"`    // digest of the policy image
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DecisionPolicy) Reset() {
	*x = DecisionPolicy{}
	mi := &file_aserto_authorizer_v2_api_decision_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionPolicy) ProtoMessage() {}

func (x *DecisionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_api_decision_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionPolicy.ProtoReflect.Descriptor instead.
func (*DecisionPolicy) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_api_decision_logs_proto_rawDescGZIP(), []int{2}
}

func (x *DecisionPolicy) GetContext() *PolicyContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DecisionPolicy) GetRegistryService() string {
	if x != nil {
		return x.RegistryService
	}
	return ""
}

func (x *DecisionPolicy) GetRegistryImage() string {
	if x != nil {
		return x.RegistryImage
	}
	return ""
}

func (x *DecisionPolicy) GetRegistryTag() string {
	if x != nil {
		return x.RegistryTag
	}
	return ""
}

func (x *DecisionPolicy) GetRegistryDigest() string {
	if x != nil {
		return x.RegistryDigest
	}
	return ""
}

var File_aserto_authorizer_v2_api_decision_logs_proto protoreflect.FileDescriptor

const file_aserto_authorizer_v2_api_decision_logs_proto_rawDesc = "" +
	"\n" +
	",aserto/authorizer/v2/api/decision_logs.proto\x12\x18aserto.authorizer.v2.api\x1a/aserto/authorizer/v2/api/identity_context.proto\x1a-aserto/authorizer/v2/api/policy_context.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x04\n" +
	"\bDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12:\n" +
	"\x04user\x18\x04 \x01(\v2&.aserto.authorizer.v2.api.DecisionUserR\x04user\x12@\n" +
	"\x06policy\x18\x05 \x01(\v2(.aserto.authorizer.v2.api.DecisionPolicyR\x06policy\x12L\n" +
	"\boutcomes\x18\x06 \x03(\v20.aserto.authorizer.v2.api.Decision.OutcomesEntryR\boutcomes\x123\n" +
	"\bresource\x18\a \x01(\v2\x17.google.protobuf.StructR\bresource\x12U\n" +
	"\vannotations\x18\b \x03(\v23.aserto.authorizer.v2.api.Decision.AnnotationsEntryR\vannotations\x1a;\n" +
	"\rOutcomesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\t\x10\n" +
	"R\ttenant_id\"y\n" +
	"\fDecisionUser\x12C\n" +
	"\acontext\x18\x01 \x01(\v2).aserto.authorizer.v2.api.IdentityContextR\acontext\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\x88\x02\n" +
	"\x0eDecisionPolicy\x12A\n" +
	"\acontext\x18\x01 \x01(\v2'.aserto.authorizer.v2.api.PolicyContextR\acontext\x12)\n" +
	"\x10registry_service\x18\x02 \x01(\tR\x0fregistryService\x12%\n" +
	"\x0eregistry_image\x18\x03 \x01(\tR\rregistryImage\x12!\n" +
	"\fregistry_tag\x18\x04 \x01(\tR\vregistryTag\x12'\n" +
	"\x0fregistry_digest\x18\x05 \x01(\tR\x0eregistryDigestJ\x04\b\x06\x10\aR\x0fpolicy_instanceB]Z@github.com/aserto-dev/go-authorizer/aserto/authorizer/v2/api;api\xaa\x02\x18Aserto.Authorizer.V2.APIb\x06proto3"

var (
	file_aserto_authorizer_v2_api_decision_logs_proto_rawDescOnce sync.Once
	file_aserto_authorizer_v2_api_decision_logs_proto_rawDescData []byte
)

func file_aserto_authorizer_v2_api_decision_logs_proto_rawDescGZIP() []byte {
	file_aserto_authorizer_v2_api_decision_logs_proto_rawDescOnce.Do(func() {
		file_aserto_authorizer_v2_api_decision_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_api_decision_logs_proto_rawDesc), len(file_aserto_authorizer_v2_api_decision_logs_proto_rawDesc)))
	})
	return file_aserto_authorizer_v2_api_decision_logs_proto_rawDescData
}

var file_aserto_authorizer_v2_api_decision_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_aserto_authorizer_v2_api_decision_logs_proto_goTypes = []any{
	(*Decision)(nil),              // 0: aserto.authorizer.v2.api.Decision
	(*DecisionUser)(nil),          // 1: aserto.authorizer.v2.api.DecisionUser
	(*DecisionPolicy)(nil),        // 2: aserto.authorizer.v2.api.DecisionPolicy
	nil,                           // 3: aserto.authorizer.v2.api.Decision.OutcomesEntry
	nil,                           // 4: aserto.authorizer.v2.api.Decision.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
	(*IdentityContext)(nil),       // 7: aserto.authorizer.v2.api.IdentityContext
	(*PolicyContext)(nil),         // 8: aserto.authorizer.v2.api.PolicyContext
}
var file_aserto_authorizer_v2_api_decision_logs_proto_depIdxs = []int32{
	5, // 0: aserto.authorizer.v2.api.Decision.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: aserto.authorizer.v2.api.Decision.user:type_name -> aserto.authorizer.v2.api.DecisionUser
	2, // 2: aserto.authorizer.v2.api.Decision.policy:type_name -> aserto.authorizer.v2.api.DecisionPolicy
	3, // 3: aserto.authorizer.v2.api.Decision.outcomes:type_name -> aserto.authorizer.v2.api.Decision.OutcomesEntry
	6, // 4: aserto.authorizer.v2.api.Decision.resource:type_name -> google.protobuf.Struct
	4, // 5: aserto.authorizer.v2.api.Decision.annotations:type_name -> aserto.authorizer.v2.api.Decision.AnnotationsEntry
	7, // 6: aserto.authorizer.v2.api.DecisionUser.context:type_name -> aserto.authorizer.v2.api.IdentityContext
	8, // 7: aserto.authorizer.v2.api.DecisionPolicy.context:type_name -> aserto.authorizer.v2.api.PolicyContext
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_aserto_authorizer_v2_api_decision_logs_proto_init() }
func file_aserto_authorizer_v2_api_decision_logs_proto_init() {
	if File_aserto_authorizer_v2_api_decision_logs_proto != nil {
		return
	}
	file_aserto_authorizer_v2_api_identity_context_proto_init()
	file_aserto_authorizer_v2_api_policy_context_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_api_decision_logs_proto_rawDesc), len(file_aserto_authorizer_v2_api_decision_logs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aserto_authorizer_v2_api_decision_logs_proto_goTypes,
		DependencyIndexes: file_aserto_authorizer_v2_api_decision_logs_proto_depIdxs,
		MessageInfos:      file_aserto_authorizer_v2_api_decision_logs_proto_msgTypes,
	}.Build()
	File_aserto_authorizer_v2_api_decision_logs_proto = out.File
	file_aserto_authorizer_v2_api_decision_logs_proto_goTypes = nil
	file_aserto_authorizer_v2_api_decision_logs_proto_depIdxs = nil
}
