// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aserto/authorizer/v2/api/identity_context.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identity types, describes the payload type of the identity field inside the IdentityContext message.
type IdentityType int32

const (
	// Unknown, value not set, requests will fail with identity type not set error.
	IdentityType_IDENTITY_TYPE_UNKNOWN IdentityType = 0
	// None, no explicit identity context set, equals anonymous.
	IdentityType_IDENTITY_TYPE_NONE IdentityType = 1
	// Sub(ject), identity field contains an oAUTH subject.
	IdentityType_IDENTITY_TYPE_SUB IdentityType = 2
	// JWT, identity field contains a JWT access token.
	IdentityType_IDENTITY_TYPE_JWT IdentityType = 3
	// Manual, propagates thw identity field as-is, without validation, into the input object.
	IdentityType_IDENTITY_TYPE_MANUAL IdentityType = 4
)

// Enum value maps for IdentityType.
var (
	IdentityType_name = map[int32]string{
		0: "IDENTITY_TYPE_UNKNOWN",
		1: "IDENTITY_TYPE_NONE",
		2: "IDENTITY_TYPE_SUB",
		3: "IDENTITY_TYPE_JWT",
		4: "IDENTITY_TYPE_MANUAL",
	}
	IdentityType_value = map[string]int32{
		"IDENTITY_TYPE_UNKNOWN": 0,
		"IDENTITY_TYPE_NONE":    1,
		"IDENTITY_TYPE_SUB":     2,
		"IDENTITY_TYPE_JWT":     3,
		"IDENTITY_TYPE_MANUAL":  4,
	}
)

func (x IdentityType) Enum() *IdentityType {
	p := new(IdentityType)
	*p = x
	return p
}

func (x IdentityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityType) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_authorizer_v2_api_identity_context_proto_enumTypes[0].Descriptor()
}

func (IdentityType) Type() protoreflect.EnumType {
	return &file_aserto_authorizer_v2_api_identity_context_proto_enumTypes[0]
}

func (x IdentityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityType.Descriptor instead.
func (IdentityType) EnumDescriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_api_identity_context_proto_rawDescGZIP(), []int{0}
}

type IdentityContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Type          IdentityType           `protobuf:"varint,2,opt,name=type,proto3,enum=aserto.authorizer.v2.api.IdentityType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityContext) Reset() {
	*x = IdentityContext{}
	mi := &file_aserto_authorizer_v2_api_identity_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityContext) ProtoMessage() {}

func (x *IdentityContext) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_api_identity_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityContext.ProtoReflect.Descriptor instead.
func (*IdentityContext) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_api_identity_context_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityContext) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *IdentityContext) GetType() IdentityType {
	if x != nil {
		return x.Type
	}
	return IdentityType_IDENTITY_TYPE_UNKNOWN
}

var File_aserto_authorizer_v2_api_identity_context_proto protoreflect.FileDescriptor

const file_aserto_authorizer_v2_api_identity_context_proto_rawDesc = "" +
	"\n" +
	"/aserto/authorizer/v2/api/identity_context.proto\x12\x18aserto.authorizer.v2.api\"i\n" +
	"\x0fIdentityContext\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.aserto.authorizer.v2.api.IdentityTypeR\x04type*\x89\x01\n" +
	"\fIdentityType\x12\x19\n" +
	"\x15IDENTITY_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12IDENTITY_TYPE_NONE\x10\x01\x12\x15\n" +
	"\x11IDENTITY_TYPE_SUB\x10\x02\x12\x15\n" +
	"\x11IDENTITY_TYPE_JWT\x10\x03\x12\x18\n" +
	"\x14IDENTITY_TYPE_MANUAL\x10\x04B]Z@github.com/aserto-dev/go-authorizer/aserto/authorizer/v2/api;api\xaa\x02\x18Aserto.Authorizer.V2.APIb\x06proto3"

var (
	file_aserto_authorizer_v2_api_identity_context_proto_rawDescOnce sync.Once
	file_aserto_authorizer_v2_api_identity_context_proto_rawDescData []byte
)

func file_aserto_authorizer_v2_api_identity_context_proto_rawDescGZIP() []byte {
	file_aserto_authorizer_v2_api_identity_context_proto_rawDescOnce.Do(func() {
		file_aserto_authorizer_v2_api_identity_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_api_identity_context_proto_rawDesc), len(file_aserto_authorizer_v2_api_identity_context_proto_rawDesc)))
	})
	return file_aserto_authorizer_v2_api_identity_context_proto_rawDescData
}

var file_aserto_authorizer_v2_api_identity_context_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aserto_authorizer_v2_api_identity_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aserto_authorizer_v2_api_identity_context_proto_goTypes = []any{
	(IdentityType)(0),       // 0: aserto.authorizer.v2.api.IdentityType
	(*IdentityContext)(nil), // 1: aserto.authorizer.v2.api.IdentityContext
}
var file_aserto_authorizer_v2_api_identity_context_proto_depIdxs = []int32{
	0, // 0: aserto.authorizer.v2.api.IdentityContext.type:type_name -> aserto.authorizer.v2.api.IdentityType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aserto_authorizer_v2_api_identity_context_proto_init() }
func file_aserto_authorizer_v2_api_identity_context_proto_init() {
	if File_aserto_authorizer_v2_api_identity_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_api_identity_context_proto_rawDesc), len(file_aserto_authorizer_v2_api_identity_context_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aserto_authorizer_v2_api_identity_context_proto_goTypes,
		DependencyIndexes: file_aserto_authorizer_v2_api_identity_context_proto_depIdxs,
		EnumInfos:         file_aserto_authorizer_v2_api_identity_context_proto_enumTypes,
		MessageInfos:      file_aserto_authorizer_v2_api_identity_context_proto_msgTypes,
	}.Build()
	File_aserto_authorizer_v2_api_identity_context_proto = out.File
	file_aserto_authorizer_v2_api_identity_context_proto_goTypes = nil
	file_aserto_authorizer_v2_api_identity_context_proto_depIdxs = nil
}
