// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aserto/authorizer/v2/api/module.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Raw           *string                `protobuf:"bytes,2,opt,name=raw,proto3,oneof" json:"raw,omitempty"`
	PackagePath   *string                `protobuf:"bytes,3,opt,name=package_path,json=packagePath,proto3,oneof" json:"package_path,omitempty"`
	Ast           *structpb.Value        `protobuf:"bytes,4,opt,name=ast,proto3,oneof" json:"ast,omitempty"`
	PackageRoot   *string                `protobuf:"bytes,5,opt,name=package_root,json=packageRoot,proto3,oneof" json:"package_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_aserto_authorizer_v2_api_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_api_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_api_module_proto_rawDescGZIP(), []int{0}
}

func (x *Module) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Module) GetRaw() string {
	if x != nil && x.Raw != nil {
		return *x.Raw
	}
	return ""
}

func (x *Module) GetPackagePath() string {
	if x != nil && x.PackagePath != nil {
		return *x.PackagePath
	}
	return ""
}

func (x *Module) GetAst() *structpb.Value {
	if x != nil {
		return x.Ast
	}
	return nil
}

func (x *Module) GetPackageRoot() string {
	if x != nil && x.PackageRoot != nil {
		return *x.PackageRoot
	}
	return ""
}

var File_aserto_authorizer_v2_api_module_proto protoreflect.FileDescriptor

const file_aserto_authorizer_v2_api_module_proto_rawDesc = "" +
	"\n" +
	"%aserto/authorizer/v2/api/module.proto\x12\x18aserto.authorizer.v2.api\x1a\x1cgoogle/protobuf/struct.proto\"\xec\x01\n" +
	"\x06Module\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x15\n" +
	"\x03raw\x18\x02 \x01(\tH\x01R\x03raw\x88\x01\x01\x12&\n" +
	"\fpackage_path\x18\x03 \x01(\tH\x02R\vpackagePath\x88\x01\x01\x12-\n" +
	"\x03ast\x18\x04 \x01(\v2\x16.google.protobuf.ValueH\x03R\x03ast\x88\x01\x01\x12&\n" +
	"\fpackage_root\x18\x05 \x01(\tH\x04R\vpackageRoot\x88\x01\x01B\x05\n" +
	"\x03_idB\x06\n" +
	"\x04_rawB\x0f\n" +
	"\r_package_pathB\x06\n" +
	"\x04_astB\x0f\n" +
	"\r_package_rootB]Z@github.com/aserto-dev/go-authorizer/aserto/authorizer/v2/api;api\xaa\x02\x18Aserto.Authorizer.V2.APIb\x06proto3"

var (
	file_aserto_authorizer_v2_api_module_proto_rawDescOnce sync.Once
	file_aserto_authorizer_v2_api_module_proto_rawDescData []byte
)

func file_aserto_authorizer_v2_api_module_proto_rawDescGZIP() []byte {
	file_aserto_authorizer_v2_api_module_proto_rawDescOnce.Do(func() {
		file_aserto_authorizer_v2_api_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_api_module_proto_rawDesc), len(file_aserto_authorizer_v2_api_module_proto_rawDesc)))
	})
	return file_aserto_authorizer_v2_api_module_proto_rawDescData
}

var file_aserto_authorizer_v2_api_module_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aserto_authorizer_v2_api_module_proto_goTypes = []any{
	(*Module)(nil),         // 0: aserto.authorizer.v2.api.Module
	(*structpb.Value)(nil), // 1: google.protobuf.Value
}
var file_aserto_authorizer_v2_api_module_proto_depIdxs = []int32{
	1, // 0: aserto.authorizer.v2.api.Module.ast:type_name -> google.protobuf.Value
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aserto_authorizer_v2_api_module_proto_init() }
func file_aserto_authorizer_v2_api_module_proto_init() {
	if File_aserto_authorizer_v2_api_module_proto != nil {
		return
	}
	file_aserto_authorizer_v2_api_module_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_api_module_proto_rawDesc), len(file_aserto_authorizer_v2_api_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aserto_authorizer_v2_api_module_proto_goTypes,
		DependencyIndexes: file_aserto_authorizer_v2_api_module_proto_depIdxs,
		MessageInfos:      file_aserto_authorizer_v2_api_module_proto_msgTypes,
	}.Build()
	File_aserto_authorizer_v2_api_module_proto = out.File
	file_aserto_authorizer_v2_api_module_proto_goTypes = nil
	file_aserto_authorizer_v2_api_module_proto_depIdxs = nil
}
