// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aserto/authorizer/v2/api/policy_context.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`           // policy path aka package name
	Decisions     []string               `protobuf:"bytes,2,rep,name=decisions,proto3" json:"decisions,omitempty"` // list (1..N) of policy decisions (aka rules)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyContext) Reset() {
	*x = PolicyContext{}
	mi := &file_aserto_authorizer_v2_api_policy_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyContext) ProtoMessage() {}

func (x *PolicyContext) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_api_policy_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyContext.ProtoReflect.Descriptor instead.
func (*PolicyContext) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_api_policy_context_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyContext) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PolicyContext) GetDecisions() []string {
	if x != nil {
		return x.Decisions
	}
	return nil
}

var File_aserto_authorizer_v2_api_policy_context_proto protoreflect.FileDescriptor

const file_aserto_authorizer_v2_api_policy_context_proto_rawDesc = "" +
	"\n" +
	"-aserto/authorizer/v2/api/policy_context.proto\x12\x18aserto.authorizer.v2.api\"A\n" +
	"\rPolicyContext\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\tdecisions\x18\x02 \x03(\tR\tdecisionsB]Z@github.com/aserto-dev/go-authorizer/aserto/authorizer/v2/api;api\xaa\x02\x18Aserto.Authorizer.V2.APIb\x06proto3"

var (
	file_aserto_authorizer_v2_api_policy_context_proto_rawDescOnce sync.Once
	file_aserto_authorizer_v2_api_policy_context_proto_rawDescData []byte
)

func file_aserto_authorizer_v2_api_policy_context_proto_rawDescGZIP() []byte {
	file_aserto_authorizer_v2_api_policy_context_proto_rawDescOnce.Do(func() {
		file_aserto_authorizer_v2_api_policy_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_api_policy_context_proto_rawDesc), len(file_aserto_authorizer_v2_api_policy_context_proto_rawDesc)))
	})
	return file_aserto_authorizer_v2_api_policy_context_proto_rawDescData
}

var file_aserto_authorizer_v2_api_policy_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aserto_authorizer_v2_api_policy_context_proto_goTypes = []any{
	(*PolicyContext)(nil), // 0: aserto.authorizer.v2.api.PolicyContext
}
var file_aserto_authorizer_v2_api_policy_context_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aserto_authorizer_v2_api_policy_context_proto_init() }
func file_aserto_authorizer_v2_api_policy_context_proto_init() {
	if File_aserto_authorizer_v2_api_policy_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_api_policy_context_proto_rawDesc), len(file_aserto_authorizer_v2_api_policy_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aserto_authorizer_v2_api_policy_context_proto_goTypes,
		DependencyIndexes: file_aserto_authorizer_v2_api_policy_context_proto_depIdxs,
		MessageInfos:      file_aserto_authorizer_v2_api_policy_context_proto_msgTypes,
	}.Build()
	File_aserto_authorizer_v2_api_policy_context_proto = out.File
	file_aserto_authorizer_v2_api_policy_context_proto_goTypes = nil
	file_aserto_authorizer_v2_api_policy_context_proto_depIdxs = nil
}
