// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aserto/authorizer/v2/authorizer.proto

package authorizer

import (
	api "github.com/aserto-dev/go-authorizer/aserto/authorizer/v2/api"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PathSeparator int32

const (
	PathSeparator_PATH_SEPARATOR_UNKNOWN PathSeparator = 0 // Value not set.
	PathSeparator_PATH_SEPARATOR_DOT     PathSeparator = 1 // Dot "." path separator
	PathSeparator_PATH_SEPARATOR_SLASH   PathSeparator = 2 // Slash "/" path separtor
)

// Enum value maps for PathSeparator.
var (
	PathSeparator_name = map[int32]string{
		0: "PATH_SEPARATOR_UNKNOWN",
		1: "PATH_SEPARATOR_DOT",
		2: "PATH_SEPARATOR_SLASH",
	}
	PathSeparator_value = map[string]int32{
		"PATH_SEPARATOR_UNKNOWN": 0,
		"PATH_SEPARATOR_DOT":     1,
		"PATH_SEPARATOR_SLASH":   2,
	}
)

func (x PathSeparator) Enum() *PathSeparator {
	p := new(PathSeparator)
	*p = x
	return p
}

func (x PathSeparator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathSeparator) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_authorizer_v2_authorizer_proto_enumTypes[0].Descriptor()
}

func (PathSeparator) Type() protoreflect.EnumType {
	return &file_aserto_authorizer_v2_authorizer_proto_enumTypes[0]
}

func (x PathSeparator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathSeparator.Descriptor instead.
func (PathSeparator) EnumDescriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{0}
}

type TraceLevel int32

const (
	TraceLevel_TRACE_LEVEL_UNKNOWN TraceLevel = 0 // Value not set.
	TraceLevel_TRACE_LEVEL_OFF     TraceLevel = 1 // ExplainOffV1   ExplainModeV1 = "off"
	TraceLevel_TRACE_LEVEL_FULL    TraceLevel = 2 // ExplainFullV1  ExplainModeV1 = "full"
	TraceLevel_TRACE_LEVEL_NOTES   TraceLevel = 3 // ExplainNotesV1 ExplainModeV1 = "notes"
	TraceLevel_TRACE_LEVEL_FAILS   TraceLevel = 4 // ExplainFailsV1 ExplainModeV1 = "fails"
)

// Enum value maps for TraceLevel.
var (
	TraceLevel_name = map[int32]string{
		0: "TRACE_LEVEL_UNKNOWN",
		1: "TRACE_LEVEL_OFF",
		2: "TRACE_LEVEL_FULL",
		3: "TRACE_LEVEL_NOTES",
		4: "TRACE_LEVEL_FAILS",
	}
	TraceLevel_value = map[string]int32{
		"TRACE_LEVEL_UNKNOWN": 0,
		"TRACE_LEVEL_OFF":     1,
		"TRACE_LEVEL_FULL":    2,
		"TRACE_LEVEL_NOTES":   3,
		"TRACE_LEVEL_FAILS":   4,
	}
)

func (x TraceLevel) Enum() *TraceLevel {
	p := new(TraceLevel)
	*p = x
	return p
}

func (x TraceLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_authorizer_v2_authorizer_proto_enumTypes[1].Descriptor()
}

func (TraceLevel) Type() protoreflect.EnumType {
	return &file_aserto_authorizer_v2_authorizer_proto_enumTypes[1]
}

func (x TraceLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceLevel.Descriptor instead.
func (TraceLevel) EnumDescriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{1}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *InfoResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *InfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *InfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{2}
}

func (x *GetPolicyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPolicyRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type GetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *api.Module            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{3}
}

func (x *GetPolicyResponse) GetResult() *api.Module {
	if x != nil {
		return x.Result
	}
	return nil
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{4}
}

func (x *ListPoliciesRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*api.Module          `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{5}
}

func (x *ListPoliciesResponse) GetResult() []*api.Module {
	if x != nil {
		return x.Result
	}
	return nil
}

type DecisionTreeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PolicyContext   *api.PolicyContext     `protobuf:"bytes,1,opt,name=policy_context,json=policyContext,proto3" json:"policy_context,omitempty"`
	IdentityContext *api.IdentityContext   `protobuf:"bytes,2,opt,name=identity_context,json=identityContext,proto3" json:"identity_context,omitempty"`
	Options         *DecisionTreeOptions   `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	ResourceContext *structpb.Struct       `protobuf:"bytes,4,opt,name=resource_context,json=resourceContext,proto3" json:"resource_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DecisionTreeRequest) Reset() {
	*x = DecisionTreeRequest{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionTreeRequest) ProtoMessage() {}

func (x *DecisionTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionTreeRequest.ProtoReflect.Descriptor instead.
func (*DecisionTreeRequest) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{6}
}

func (x *DecisionTreeRequest) GetPolicyContext() *api.PolicyContext {
	if x != nil {
		return x.PolicyContext
	}
	return nil
}

func (x *DecisionTreeRequest) GetIdentityContext() *api.IdentityContext {
	if x != nil {
		return x.IdentityContext
	}
	return nil
}

func (x *DecisionTreeRequest) GetOptions() *DecisionTreeOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *DecisionTreeRequest) GetResourceContext() *structpb.Struct {
	if x != nil {
		return x.ResourceContext
	}
	return nil
}

type DecisionTreeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathSeparator PathSeparator          `protobuf:"varint,1,opt,name=path_separator,json=pathSeparator,proto3,enum=aserto.authorizer.v2.PathSeparator" json:"path_separator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionTreeOptions) Reset() {
	*x = DecisionTreeOptions{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionTreeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionTreeOptions) ProtoMessage() {}

func (x *DecisionTreeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionTreeOptions.ProtoReflect.Descriptor instead.
func (*DecisionTreeOptions) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{7}
}

func (x *DecisionTreeOptions) GetPathSeparator() PathSeparator {
	if x != nil {
		return x.PathSeparator
	}
	return PathSeparator_PATH_SEPARATOR_UNKNOWN
}

type DecisionTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathRoot      string                 `protobuf:"bytes,1,opt,name=path_root,json=pathRoot,proto3" json:"path_root,omitempty"`
	Path          *structpb.Struct       `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionTreeResponse) Reset() {
	*x = DecisionTreeResponse{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionTreeResponse) ProtoMessage() {}

func (x *DecisionTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionTreeResponse.ProtoReflect.Descriptor instead.
func (*DecisionTreeResponse) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{8}
}

func (x *DecisionTreeResponse) GetPathRoot() string {
	if x != nil {
		return x.PathRoot
	}
	return ""
}

func (x *DecisionTreeResponse) GetPath() *structpb.Struct {
	if x != nil {
		return x.Path
	}
	return nil
}

type IsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PolicyContext   *api.PolicyContext     `protobuf:"bytes,1,opt,name=policy_context,json=policyContext,proto3" json:"policy_context,omitempty"`
	IdentityContext *api.IdentityContext   `protobuf:"bytes,2,opt,name=identity_context,json=identityContext,proto3" json:"identity_context,omitempty"`
	ResourceContext *structpb.Struct       `protobuf:"bytes,3,opt,name=resource_context,json=resourceContext,proto3" json:"resource_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IsRequest) Reset() {
	*x = IsRequest{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsRequest) ProtoMessage() {}

func (x *IsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsRequest.ProtoReflect.Descriptor instead.
func (*IsRequest) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{9}
}

func (x *IsRequest) GetPolicyContext() *api.PolicyContext {
	if x != nil {
		return x.PolicyContext
	}
	return nil
}

func (x *IsRequest) GetIdentityContext() *api.IdentityContext {
	if x != nil {
		return x.IdentityContext
	}
	return nil
}

func (x *IsRequest) GetResourceContext() *structpb.Struct {
	if x != nil {
		return x.ResourceContext
	}
	return nil
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Is            bool                   `protobuf:"varint,2,opt,name=is,proto3" json:"is,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{10}
}

func (x *Decision) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *Decision) GetIs() bool {
	if x != nil {
		return x.Is
	}
	return false
}

type IsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*Decision            `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsResponse) Reset() {
	*x = IsResponse{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsResponse) ProtoMessage() {}

func (x *IsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsResponse.ProtoReflect.Descriptor instead.
func (*IsResponse) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{11}
}

func (x *IsResponse) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type QueryOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       bool                   `protobuf:"varint,1,opt,name=metrics,proto3" json:"metrics,omitempty"`                                  // default false
	Instrument    bool                   `protobuf:"varint,2,opt,name=instrument,proto3" json:"instrument,omitempty"`                            // default false
	Trace         TraceLevel             `protobuf:"varint,3,opt,name=trace,proto3,enum=aserto.authorizer.v2.TraceLevel" json:"trace,omitempty"` // default ExplainOffV1
	TraceSummary  bool                   `protobuf:"varint,4,opt,name=trace_summary,json=traceSummary,proto3" json:"trace_summary,omitempty"`    // default false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{12}
}

func (x *QueryOptions) GetMetrics() bool {
	if x != nil {
		return x.Metrics
	}
	return false
}

func (x *QueryOptions) GetInstrument() bool {
	if x != nil {
		return x.Instrument
	}
	return false
}

func (x *QueryOptions) GetTrace() TraceLevel {
	if x != nil {
		return x.Trace
	}
	return TraceLevel_TRACE_LEVEL_UNKNOWN
}

func (x *QueryOptions) GetTraceSummary() bool {
	if x != nil {
		return x.TraceSummary
	}
	return false
}

type QueryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Input           string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Options         *QueryOptions          `protobuf:"bytes,3,opt,name=options,proto3,oneof" json:"options,omitempty"`
	PolicyContext   *api.PolicyContext     `protobuf:"bytes,4,opt,name=policy_context,json=policyContext,proto3,oneof" json:"policy_context,omitempty"`
	IdentityContext *api.IdentityContext   `protobuf:"bytes,5,opt,name=identity_context,json=identityContext,proto3,oneof" json:"identity_context,omitempty"`
	ResourceContext *structpb.Struct       `protobuf:"bytes,6,opt,name=resource_context,json=resourceContext,proto3,oneof" json:"resource_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{13}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *QueryRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QueryRequest) GetPolicyContext() *api.PolicyContext {
	if x != nil {
		return x.PolicyContext
	}
	return nil
}

func (x *QueryRequest) GetIdentityContext() *api.IdentityContext {
	if x != nil {
		return x.IdentityContext
	}
	return nil
}

func (x *QueryRequest) GetResourceContext() *structpb.Struct {
	if x != nil {
		return x.ResourceContext
	}
	return nil
}

type CompileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Input           string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Unknowns        []string               `protobuf:"bytes,3,rep,name=unknowns,proto3" json:"unknowns,omitempty"`
	DisableInlining []string               `protobuf:"bytes,4,rep,name=disable_inlining,json=disableInlining,proto3" json:"disable_inlining,omitempty"`
	Options         *QueryOptions          `protobuf:"bytes,5,opt,name=options,proto3,oneof" json:"options,omitempty"`
	PolicyContext   *api.PolicyContext     `protobuf:"bytes,6,opt,name=policy_context,json=policyContext,proto3,oneof" json:"policy_context,omitempty"`
	IdentityContext *api.IdentityContext   `protobuf:"bytes,7,opt,name=identity_context,json=identityContext,proto3,oneof" json:"identity_context,omitempty"`
	ResourceContext *structpb.Struct       `protobuf:"bytes,8,opt,name=resource_context,json=resourceContext,proto3,oneof" json:"resource_context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{14}
}

func (x *CompileRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CompileRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *CompileRequest) GetUnknowns() []string {
	if x != nil {
		return x.Unknowns
	}
	return nil
}

func (x *CompileRequest) GetDisableInlining() []string {
	if x != nil {
		return x.DisableInlining
	}
	return nil
}

func (x *CompileRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CompileRequest) GetPolicyContext() *api.PolicyContext {
	if x != nil {
		return x.PolicyContext
	}
	return nil
}

func (x *CompileRequest) GetIdentityContext() *api.IdentityContext {
	if x != nil {
		return x.IdentityContext
	}
	return nil
}

func (x *CompileRequest) GetResourceContext() *structpb.Struct {
	if x != nil {
		return x.ResourceContext
	}
	return nil
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *structpb.Struct       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Metrics       *structpb.Struct       `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Trace         []*structpb.Struct     `protobuf:"bytes,3,rep,name=trace,proto3" json:"trace,omitempty"`
	TraceSummary  []string               `protobuf:"bytes,4,rep,name=trace_summary,json=traceSummary,proto3" json:"trace_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{15}
}

func (x *CompileResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompileResponse) GetMetrics() *structpb.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *CompileResponse) GetTrace() []*structpb.Struct {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *CompileResponse) GetTraceSummary() []string {
	if x != nil {
		return x.TraceSummary
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *structpb.Struct       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Metrics       *structpb.Struct       `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Trace         []*structpb.Struct     `protobuf:"bytes,3,rep,name=trace,proto3" json:"trace,omitempty"`
	TraceSummary  []string               `protobuf:"bytes,4,rep,name=trace_summary,json=traceSummary,proto3" json:"trace_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_authorizer_v2_authorizer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP(), []int{16}
}

func (x *QueryResponse) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *QueryResponse) GetMetrics() *structpb.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *QueryResponse) GetTrace() []*structpb.Struct {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *QueryResponse) GetTraceSummary() []string {
	if x != nil {
		return x.TraceSummary
	}
	return nil
}

var File_aserto_authorizer_v2_authorizer_proto protoreflect.FileDescriptor

const file_aserto_authorizer_v2_authorizer_proto_rawDesc = "" +
	"\n" +
	"%aserto/authorizer/v2/authorizer.proto\x12\x14aserto.authorizer.v2\x1a/aserto/authorizer/v2/api/identity_context.proto\x1a%aserto/authorizer/v2/api/module.proto\x1a-aserto/authorizer/v2/api/policy_context.proto\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\r\n" +
	"\vInfoRequest\"x\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\"t\n" +
	"\x10GetPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMaskJ\x04\b\x03\x10\x04R\x0fpolicy_instance\"M\n" +
	"\x11GetPolicyResponse\x128\n" +
	"\x06result\x18\x01 \x01(\v2 .aserto.authorizer.v2.api.ModuleR\x06result\"g\n" +
	"\x13ListPoliciesRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMaskJ\x04\b\x03\x10\x04R\x0fpolicy_instance\"P\n" +
	"\x14ListPoliciesResponse\x128\n" +
	"\x06result\x18\x01 \x03(\v2 .aserto.authorizer.v2.api.ModuleR\x06result\"\xdb\x02\n" +
	"\x13DecisionTreeRequest\x12N\n" +
	"\x0epolicy_context\x18\x01 \x01(\v2'.aserto.authorizer.v2.api.PolicyContextR\rpolicyContext\x12T\n" +
	"\x10identity_context\x18\x02 \x01(\v2).aserto.authorizer.v2.api.IdentityContextR\x0fidentityContext\x12C\n" +
	"\aoptions\x18\x03 \x01(\v2).aserto.authorizer.v2.DecisionTreeOptionsR\aoptions\x12B\n" +
	"\x10resource_context\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0fresourceContextJ\x04\b\x05\x10\x06R\x0fpolicy_instance\"g\n" +
	"\x13DecisionTreeOptions\x12J\n" +
	"\x0epath_separator\x18\x01 \x01(\x0e2#.aserto.authorizer.v2.PathSeparatorR\rpathSeparatorJ\x04\b\x02\x10\x03\"f\n" +
	"\x14DecisionTreeResponse\x12\x1b\n" +
	"\tpath_root\x18\x01 \x01(\tR\bpathRoot\x12+\n" +
	"\x04path\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04pathJ\x04\b\x02\x10\x03\"\x8c\x02\n" +
	"\tIsRequest\x12N\n" +
	"\x0epolicy_context\x18\x01 \x01(\v2'.aserto.authorizer.v2.api.PolicyContextR\rpolicyContext\x12T\n" +
	"\x10identity_context\x18\x02 \x01(\v2).aserto.authorizer.v2.api.IdentityContextR\x0fidentityContext\x12B\n" +
	"\x10resource_context\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0fresourceContextJ\x04\b\x04\x10\x05R\x0fpolicy_instance\"6\n" +
	"\bDecision\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x0e\n" +
	"\x02is\x18\x02 \x01(\bR\x02is\"J\n" +
	"\n" +
	"IsResponse\x12<\n" +
	"\tdecisions\x18\x01 \x03(\v2\x1e.aserto.authorizer.v2.DecisionR\tdecisions\"\xa5\x01\n" +
	"\fQueryOptions\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\bR\ametrics\x12\x1e\n" +
	"\n" +
	"instrument\x18\x02 \x01(\bR\n" +
	"instrument\x126\n" +
	"\x05trace\x18\x03 \x01(\x0e2 .aserto.authorizer.v2.TraceLevelR\x05trace\x12#\n" +
	"\rtrace_summary\x18\x04 \x01(\bR\ftraceSummary\"\xd6\x03\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12A\n" +
	"\aoptions\x18\x03 \x01(\v2\".aserto.authorizer.v2.QueryOptionsH\x00R\aoptions\x88\x01\x01\x12S\n" +
	"\x0epolicy_context\x18\x04 \x01(\v2'.aserto.authorizer.v2.api.PolicyContextH\x01R\rpolicyContext\x88\x01\x01\x12Y\n" +
	"\x10identity_context\x18\x05 \x01(\v2).aserto.authorizer.v2.api.IdentityContextH\x02R\x0fidentityContext\x88\x01\x01\x12G\n" +
	"\x10resource_context\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x03R\x0fresourceContext\x88\x01\x01B\n" +
	"\n" +
	"\b_optionsB\x11\n" +
	"\x0f_policy_contextB\x13\n" +
	"\x11_identity_contextB\x13\n" +
	"\x11_resource_contextJ\x04\b\a\x10\bR\x0fpolicy_instance\"\x9f\x04\n" +
	"\x0eCompileRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x1a\n" +
	"\bunknowns\x18\x03 \x03(\tR\bunknowns\x12)\n" +
	"\x10disable_inlining\x18\x04 \x03(\tR\x0fdisableInlining\x12A\n" +
	"\aoptions\x18\x05 \x01(\v2\".aserto.authorizer.v2.QueryOptionsH\x00R\aoptions\x88\x01\x01\x12S\n" +
	"\x0epolicy_context\x18\x06 \x01(\v2'.aserto.authorizer.v2.api.PolicyContextH\x01R\rpolicyContext\x88\x01\x01\x12Y\n" +
	"\x10identity_context\x18\a \x01(\v2).aserto.authorizer.v2.api.IdentityContextH\x02R\x0fidentityContext\x88\x01\x01\x12G\n" +
	"\x10resource_context\x18\b \x01(\v2\x17.google.protobuf.StructH\x03R\x0fresourceContext\x88\x01\x01B\n" +
	"\n" +
	"\b_optionsB\x11\n" +
	"\x0f_policy_contextB\x13\n" +
	"\x11_identity_contextB\x13\n" +
	"\x11_resource_contextJ\x04\b\t\x10\n" +
	"R\x0fpolicy_instance\"\xc9\x01\n" +
	"\x0fCompileResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06result\x121\n" +
	"\ametrics\x18\x02 \x01(\v2\x17.google.protobuf.StructR\ametrics\x12-\n" +
	"\x05trace\x18\x03 \x03(\v2\x17.google.protobuf.StructR\x05trace\x12#\n" +
	"\rtrace_summary\x18\x04 \x03(\tR\ftraceSummary\"\xcb\x01\n" +
	"\rQueryResponse\x123\n" +
	"\bresponse\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bresponse\x121\n" +
	"\ametrics\x18\x02 \x01(\v2\x17.google.protobuf.StructR\ametrics\x12-\n" +
	"\x05trace\x18\x03 \x03(\v2\x17.google.protobuf.StructR\x05trace\x12#\n" +
	"\rtrace_summary\x18\x04 \x03(\tR\ftraceSummary*]\n" +
	"\rPathSeparator\x12\x1a\n" +
	"\x16PATH_SEPARATOR_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12PATH_SEPARATOR_DOT\x10\x01\x12\x18\n" +
	"\x14PATH_SEPARATOR_SLASH\x10\x02*~\n" +
	"\n" +
	"TraceLevel\x12\x17\n" +
	"\x13TRACE_LEVEL_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fTRACE_LEVEL_OFF\x10\x01\x12\x14\n" +
	"\x10TRACE_LEVEL_FULL\x10\x02\x12\x15\n" +
	"\x11TRACE_LEVEL_NOTES\x10\x03\x12\x15\n" +
	"\x11TRACE_LEVEL_FAILS\x10\x042\x99\r\n" +
	"\n" +
	"Authorizer\x12\x91\x02\n" +
	"\fDecisionTree\x12).aserto.authorizer.v2.DecisionTreeRequest\x1a*.aserto.authorizer.v2.DecisionTreeResponse\"\xa9\x01\x92A\x80\x01\n" +
	"\n" +
	"Authorizer\x12\rDecision tree\x1a1Returns decision tree for given identity context.*\x18authorizer.decision_treeb\x16\n" +
	"\x14\n" +
	"\x10AuthorizerAPIKey\x12\x00\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v2/authz/decisiontree\x12\x8f\x02\n" +
	"\x02Is\x12\x1f.aserto.authorizer.v2.IsRequest\x1a .aserto.authorizer.v2.IsResponse\"\xc5\x01\x92A\xa6\x01\n" +
	"\n" +
	"Authorizer\x12\x0fIs (authorized)\x1a`Determines if identity context is authorized to access the resource guarded by the given policy.*\rauthorizer.isb\x16\n" +
	"\x14\n" +
	"\x10AuthorizerAPIKey\x12\x00\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v2/authz/is\x12\xe6\x01\n" +
	"\x05Query\x12\".aserto.authorizer.v2.QueryRequest\x1a#.aserto.authorizer.v2.QueryResponse\"\x93\x01\x92Ar\n" +
	"\n" +
	"Authorizer\x12\x05Query\x1a3Executes a rego query on the loaded policy runtime.*\x10authorizer.queryb\x16\n" +
	"\x14\n" +
	"\x10AuthorizerAPIKey\x12\x00\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v2/authz/query\x12\xf5\x01\n" +
	"\aCompile\x12$.aserto.authorizer.v2.CompileRequest\x1a%.aserto.authorizer.v2.CompileResponse\"\x9c\x01\x92Ay\n" +
	"\n" +
	"Authorizer\x12\aCompile\x1a6Executes a partial query on the loaded policy runtime.*\x12authorizer.compileb\x16\n" +
	"\x14\n" +
	"\x10AuthorizerAPIKey\x12\x00\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v2/authz/compile\x12\xf2\x01\n" +
	"\fListPolicies\x12).aserto.authorizer.v2.ListPoliciesRequest\x1a*.aserto.authorizer.v2.ListPoliciesResponse\"\x8a\x01\x92Ao\n" +
	"\x06Policy\x12\rList Policies\x1a/Lists the policy modules for the policy bundle.*\rpolicies.listb\x16\n" +
	"\x14\n" +
	"\x10AuthorizerAPIKey\x12\x00\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v2/policies\x12\xf0\x01\n" +
	"\tGetPolicy\x12&.aserto.authorizer.v2.GetPolicyRequest\x1a'.aserto.authorizer.v2.GetPolicyResponse\"\x91\x01\x92Al\n" +
	"\x06Policy\x12\n" +
	"Get Policy\x1a0Gets the policy modules for the given module Id.*\fpolicies.getb\x16\n" +
	"\x14\n" +
	"\x10AuthorizerAPIKey\x12\x00\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v2/policies/{id=*/**}\x12\x9b\x01\n" +
	"\x04Info\x12!.aserto.authorizer.v2.InfoRequest\x1a\".aserto.authorizer.v2.InfoResponse\"L\x92A5\n" +
	"\x04Info\x12\x04Info\x1a\x1bReturn version information.*\binfo.getb\x00\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v2/infoB\xf1\x03\x92A\x91\x03\x12\xbf\x01\n" +
	"\x12Authorizer Service\"O\n" +
	"\fAserto, Inc.\x12+https://github.com/aserto-dev/pb-authorizer\x1a\x12support@aserto.com*S\n" +
	"\x12Apache 2.0 License\x12=https://github.com/aserto-dev/pb-authorizer/blob/main/LICENSE2\x032.1*\x02\x01\x022\x10application/json:\x10application/jsonZ)\n" +
	"'\n" +
	"\x10AuthorizerAPIKey\x12\x13\b\x02\x1a\rauthorization \x02b\x16\n" +
	"\x14\n" +
	"\x10AuthorizerAPIKey\x12\x00rb\n" +
	"\x19Authorizer API Reference.\x12Ehttps://github.com/aserto-dev/pb-authorizer/blob/main/html/index.htmlZCgithub.com/aserto-dev/go-authorizer/aserto/authorizer/v2;authorizer\xaa\x02\x14Aserto.Authorizer.V2b\x06proto3"

var (
	file_aserto_authorizer_v2_authorizer_proto_rawDescOnce sync.Once
	file_aserto_authorizer_v2_authorizer_proto_rawDescData []byte
)

func file_aserto_authorizer_v2_authorizer_proto_rawDescGZIP() []byte {
	file_aserto_authorizer_v2_authorizer_proto_rawDescOnce.Do(func() {
		file_aserto_authorizer_v2_authorizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_authorizer_proto_rawDesc), len(file_aserto_authorizer_v2_authorizer_proto_rawDesc)))
	})
	return file_aserto_authorizer_v2_authorizer_proto_rawDescData
}

var file_aserto_authorizer_v2_authorizer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_aserto_authorizer_v2_authorizer_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_aserto_authorizer_v2_authorizer_proto_goTypes = []any{
	(PathSeparator)(0),            // 0: aserto.authorizer.v2.PathSeparator
	(TraceLevel)(0),               // 1: aserto.authorizer.v2.TraceLevel
	(*InfoRequest)(nil),           // 2: aserto.authorizer.v2.InfoRequest
	(*InfoResponse)(nil),          // 3: aserto.authorizer.v2.InfoResponse
	(*GetPolicyRequest)(nil),      // 4: aserto.authorizer.v2.GetPolicyRequest
	(*GetPolicyResponse)(nil),     // 5: aserto.authorizer.v2.GetPolicyResponse
	(*ListPoliciesRequest)(nil),   // 6: aserto.authorizer.v2.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),  // 7: aserto.authorizer.v2.ListPoliciesResponse
	(*DecisionTreeRequest)(nil),   // 8: aserto.authorizer.v2.DecisionTreeRequest
	(*DecisionTreeOptions)(nil),   // 9: aserto.authorizer.v2.DecisionTreeOptions
	(*DecisionTreeResponse)(nil),  // 10: aserto.authorizer.v2.DecisionTreeResponse
	(*IsRequest)(nil),             // 11: aserto.authorizer.v2.IsRequest
	(*Decision)(nil),              // 12: aserto.authorizer.v2.Decision
	(*IsResponse)(nil),            // 13: aserto.authorizer.v2.IsResponse
	(*QueryOptions)(nil),          // 14: aserto.authorizer.v2.QueryOptions
	(*QueryRequest)(nil),          // 15: aserto.authorizer.v2.QueryRequest
	(*CompileRequest)(nil),        // 16: aserto.authorizer.v2.CompileRequest
	(*CompileResponse)(nil),       // 17: aserto.authorizer.v2.CompileResponse
	(*QueryResponse)(nil),         // 18: aserto.authorizer.v2.QueryResponse
	(*fieldmaskpb.FieldMask)(nil), // 19: google.protobuf.FieldMask
	(*api.Module)(nil),            // 20: aserto.authorizer.v2.api.Module
	(*api.PolicyContext)(nil),     // 21: aserto.authorizer.v2.api.PolicyContext
	(*api.IdentityContext)(nil),   // 22: aserto.authorizer.v2.api.IdentityContext
	(*structpb.Struct)(nil),       // 23: google.protobuf.Struct
}
var file_aserto_authorizer_v2_authorizer_proto_depIdxs = []int32{
	19, // 0: aserto.authorizer.v2.GetPolicyRequest.field_mask:type_name -> google.protobuf.FieldMask
	20, // 1: aserto.authorizer.v2.GetPolicyResponse.result:type_name -> aserto.authorizer.v2.api.Module
	19, // 2: aserto.authorizer.v2.ListPoliciesRequest.field_mask:type_name -> google.protobuf.FieldMask
	20, // 3: aserto.authorizer.v2.ListPoliciesResponse.result:type_name -> aserto.authorizer.v2.api.Module
	21, // 4: aserto.authorizer.v2.DecisionTreeRequest.policy_context:type_name -> aserto.authorizer.v2.api.PolicyContext
	22, // 5: aserto.authorizer.v2.DecisionTreeRequest.identity_context:type_name -> aserto.authorizer.v2.api.IdentityContext
	9,  // 6: aserto.authorizer.v2.DecisionTreeRequest.options:type_name -> aserto.authorizer.v2.DecisionTreeOptions
	23, // 7: aserto.authorizer.v2.DecisionTreeRequest.resource_context:type_name -> google.protobuf.Struct
	0,  // 8: aserto.authorizer.v2.DecisionTreeOptions.path_separator:type_name -> aserto.authorizer.v2.PathSeparator
	23, // 9: aserto.authorizer.v2.DecisionTreeResponse.path:type_name -> google.protobuf.Struct
	21, // 10: aserto.authorizer.v2.IsRequest.policy_context:type_name -> aserto.authorizer.v2.api.PolicyContext
	22, // 11: aserto.authorizer.v2.IsRequest.identity_context:type_name -> aserto.authorizer.v2.api.IdentityContext
	23, // 12: aserto.authorizer.v2.IsRequest.resource_context:type_name -> google.protobuf.Struct
	12, // 13: aserto.authorizer.v2.IsResponse.decisions:type_name -> aserto.authorizer.v2.Decision
	1,  // 14: aserto.authorizer.v2.QueryOptions.trace:type_name -> aserto.authorizer.v2.TraceLevel
	14, // 15: aserto.authorizer.v2.QueryRequest.options:type_name -> aserto.authorizer.v2.QueryOptions
	21, // 16: aserto.authorizer.v2.QueryRequest.policy_context:type_name -> aserto.authorizer.v2.api.PolicyContext
	22, // 17: aserto.authorizer.v2.QueryRequest.identity_context:type_name -> aserto.authorizer.v2.api.IdentityContext
	23, // 18: aserto.authorizer.v2.QueryRequest.resource_context:type_name -> google.protobuf.Struct
	14, // 19: aserto.authorizer.v2.CompileRequest.options:type_name -> aserto.authorizer.v2.QueryOptions
	21, // 20: aserto.authorizer.v2.CompileRequest.policy_context:type_name -> aserto.authorizer.v2.api.PolicyContext
	22, // 21: aserto.authorizer.v2.CompileRequest.identity_context:type_name -> aserto.authorizer.v2.api.IdentityContext
	23, // 22: aserto.authorizer.v2.CompileRequest.resource_context:type_name -> google.protobuf.Struct
	23, // 23: aserto.authorizer.v2.CompileResponse.result:type_name -> google.protobuf.Struct
	23, // 24: aserto.authorizer.v2.CompileResponse.metrics:type_name -> google.protobuf.Struct
	23, // 25: aserto.authorizer.v2.CompileResponse.trace:type_name -> google.protobuf.Struct
	23, // 26: aserto.authorizer.v2.QueryResponse.response:type_name -> google.protobuf.Struct
	23, // 27: aserto.authorizer.v2.QueryResponse.metrics:type_name -> google.protobuf.Struct
	23, // 28: aserto.authorizer.v2.QueryResponse.trace:type_name -> google.protobuf.Struct
	8,  // 29: aserto.authorizer.v2.Authorizer.DecisionTree:input_type -> aserto.authorizer.v2.DecisionTreeRequest
	11, // 30: aserto.authorizer.v2.Authorizer.Is:input_type -> aserto.authorizer.v2.IsRequest
	15, // 31: aserto.authorizer.v2.Authorizer.Query:input_type -> aserto.authorizer.v2.QueryRequest
	16, // 32: aserto.authorizer.v2.Authorizer.Compile:input_type -> aserto.authorizer.v2.CompileRequest
	6,  // 33: aserto.authorizer.v2.Authorizer.ListPolicies:input_type -> aserto.authorizer.v2.ListPoliciesRequest
	4,  // 34: aserto.authorizer.v2.Authorizer.GetPolicy:input_type -> aserto.authorizer.v2.GetPolicyRequest
	2,  // 35: aserto.authorizer.v2.Authorizer.Info:input_type -> aserto.authorizer.v2.InfoRequest
	10, // 36: aserto.authorizer.v2.Authorizer.DecisionTree:output_type -> aserto.authorizer.v2.DecisionTreeResponse
	13, // 37: aserto.authorizer.v2.Authorizer.Is:output_type -> aserto.authorizer.v2.IsResponse
	18, // 38: aserto.authorizer.v2.Authorizer.Query:output_type -> aserto.authorizer.v2.QueryResponse
	17, // 39: aserto.authorizer.v2.Authorizer.Compile:output_type -> aserto.authorizer.v2.CompileResponse
	7,  // 40: aserto.authorizer.v2.Authorizer.ListPolicies:output_type -> aserto.authorizer.v2.ListPoliciesResponse
	5,  // 41: aserto.authorizer.v2.Authorizer.GetPolicy:output_type -> aserto.authorizer.v2.GetPolicyResponse
	3,  // 42: aserto.authorizer.v2.Authorizer.Info:output_type -> aserto.authorizer.v2.InfoResponse
	36, // [36:43] is the sub-list for method output_type
	29, // [29:36] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_aserto_authorizer_v2_authorizer_proto_init() }
func file_aserto_authorizer_v2_authorizer_proto_init() {
	if File_aserto_authorizer_v2_authorizer_proto != nil {
		return
	}
	file_aserto_authorizer_v2_authorizer_proto_msgTypes[13].OneofWrappers = []any{}
	file_aserto_authorizer_v2_authorizer_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_authorizer_v2_authorizer_proto_rawDesc), len(file_aserto_authorizer_v2_authorizer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aserto_authorizer_v2_authorizer_proto_goTypes,
		DependencyIndexes: file_aserto_authorizer_v2_authorizer_proto_depIdxs,
		EnumInfos:         file_aserto_authorizer_v2_authorizer_proto_enumTypes,
		MessageInfos:      file_aserto_authorizer_v2_authorizer_proto_msgTypes,
	}.Build()
	File_aserto_authorizer_v2_authorizer_proto = out.File
	file_aserto_authorizer_v2_authorizer_proto_goTypes = nil
	file_aserto_authorizer_v2_authorizer_proto_depIdxs = nil
}
